
#ifndef GUARD_CONSTANTS_BATTLE_PARTNERS_H
#define GUARD_CONSTANTS_BATTLE_PARTNERS_H

#define PARTNER_NONE                0
#define PARTNER_STEVEN              1
#define PARTNER_DAWN                2
#define PARTNER_BRENDAN_TREECKO     3
#define PARTNER_BRENDAN_TORCHIC     4
#define PARTNER_BRENDAN_MUDKIP      5
#define PARTNER_MAY_TREECKO         6
#define PARTNER_MAY_TORCHIC         7
#define PARTNER_MAY_MUDKIP          8
#define PARTNER_JAYDEN              9


#endif  // GUARD_CONSTANTS_BATTLE_PARTNERS_H
