gText_WouldYouLikeToRestYourPkmn::
	.string "Hello, and welcome to\n"
	.string "the Pokémon Center.\p"
	.string "We restore your tired Pokémon\n"
	.string "to full health.\p"
	.string "Would you like to rest your Pokémon?$"

gText_IllTakeYourPkmn::
	.string "Okay, I'll take your Pokémon\n"
	.string "for a few seconds.$"

gText_RestoredPkmnToFullHealth::
	.string "Thank you for waiting.\p"
	.string "We've restored your Pokémon\n"
	.string "to full health.$"

gText_WeHopeToSeeYouAgain::
	.string "We hope to see you again!$"

gText_WelcomeCutShort::
	.string "Hello, and welcome to\n"
	.string "the Pokémon Center.\p"
	.string "We restore your tired Pokémon\n"
	.string "to full health.\p"
	.string "Would you like to…$"

gText_NoticesGoldCard::
	.string "Th-that card…\n"
	.string "Could it be… The Gold Card?!\p"
	.string "Oh, the gold color is brilliant!\n"
	.string "The four stars seem to sparkle!\p"
	.string "I've seen several Trainers with\n"
	.string "a Silver Card before, but, {PLAYER},\l"
	.string "you're the first Trainer I've ever\l"
	.string "seen with a Gold Card!\p"
	.string "Okay, {PLAYER}, please allow me\n"
	.string "the honor of resting your Pokémon!$"

gText_YouWantTheUsual::
	.string "I'm delighted to see you, {PLAYER}!\n"
	.string "You want the usual, am I right?$"

gText_IllTakeYourPkmn2::
	.string "Okay, I'll take your Pokémon\n"
	.string "for a few seconds.$"

gText_ThankYouForWaiting::
	.string "Thank you for waiting.$"

gText_WeHopeToSeeYouAgain2::
	.string "We hope to see you again!$"

gText_DoYouNeedSomething::
    .string "Hi there! What do you need?$"

gText_MysteryGiftOption::
    .string "Mystery Gifts$"

gText_LevelCap::
    .string "My Level Cap$"

gText_ChangeBall::
    .string "Change Pokéball$"

gText_WhatBall::
    .string "OK. Pick your Ball.$"

gText_PokeBall::
    .string "Poké Ball$"

gText_GreatBall::
    .string "Great Ball$"

gText_UltraBall::
    .string "Ultra Ball$"

gText_SafariBall::
    .string "Safari Ball$"

gText_FastBall::
    .string "Fast Ball$"

gText_LevelBall::
    .string "Level Ball$"

gText_LureBall::
    .string "Lure Ball$"

gText_HeavyBall::
    .string "Heavy Ball$"

gText_LoveBall::
    .string "Love Ball$"

gText_FriendBall::
    .string "Friend Ball$"

gText_MoonBall::
    .string "Moon Ball$"

gText_SportBall::
    .string "Sport Ball$"

gText_NetBall::
    .string "Net Ball$"

gText_DiveBall::
    .string "Dive Ball$"

gText_NestBall::
    .string "Nest Ball$"

gText_RepeatBall::
    .string "Repeat Ball$"

gText_TimerBall::
    .string "Timer Ball$"

gText_LuxuryBall::
    .string "Luxury Ball$"

gText_PremierBall::
    .string "Premier Ball$"

gText_DuskBall::
    .string "Dusk Ball$"

gText_HealBall::
    .string "Heal Ball$"

gText_QuickBall::
    .string "Quick Ball$"

gText_ParkBall::
    .string "Park Ball$"

gText_DreamBall::
    .string "Dream Ball$"

gText_BeastBall::
    .string "Beast Ball$"

ThereYouGo::
    .string "There you go.\n"
    .string "Your Ball has been changed!$"

gText_TheWattsonCap::
	.string "The current level cap is 29.$"

gText_TheBrawlyCap::
	.string "The current level cap is 22.$"

gText_TheFlanCap::
	.string "The current level cap is 46.$"

gText_TheNormanCap::
	.string "The current level cap is 53.$"

gText_TheWinonaCap::
	.string "The current level cap is 64.$"

gText_TheTateLizaCap::
	.string "The current level cap is 75.$"

gText_TheJuanCap::
	.string "The current level cap is 83.$"

gText_TheLeagueCap::
	.string "The current level cap is 91.$"

gText_NoCap::
	.string "Since you're the Champion, there is no\nLevel Cap, congratulations!$"

gText_UnknownCap::
	.string "The current level cap is undetermined.$"

gText_TheRoxanneCap::
	.string "The current level cap is 17.$"

gText_PkmnCenterChallenge_NoVisitsLeft:: @ tx_difficulty_challenge
    .string "Sorry, but you are playing with\n"
    .string "the Pokécenter challenge!\p"
    .string "Good luck!{PAUSE_UNTIL_PRESS}$"
